site_name: Ostrich Web Services (OWS)
site_url: https://docs.ostrich.ag

copyright: Copyright &copy; 2023 DeepAgro.com

nav:
  - Inicio: index.md
  - Acerca de DeepAgro OWS:
      - Breve Introducción: ows/intro.md
      - Arquitectura: ows/arch.md
  - Acerca de DeepAgro Explorer: explorer.md
  - Servicios:
      - Auth service: services/auth.md
      - Settings service: services/settings.md
      - Notifications service: services/notifications.md
      - Datalake service: services/datalake.md
      - Annotations service: services/annotations.md
      - Uploader service: services/uploader.md
  - Releases:
      - Auth service: releases/auth.md
      - Settings service: releases/settings.md
      - Notifications service: releases/notifications.md
      - Datalake service: releases/datalake.md
      - Annotations service: releases/annotations.md
      - Uploader service: releases/uploader.md

theme:
  name: material
  logo: img/da-icon-white.png
  favicon: img/favicon.ico

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  analytics:
    provider: google
    property: !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
