site_name: DeepAgro Ostrich Web Services (OWS)
site_url: https://docs.ostrich.ag

title: DeepAgro Ostrich web services (OWS)
summary: A brief description about OWS
authors:
  - Luciano Perezzini

copyright: Copyright &copy; 2023 DeepAgro.com

nav:
  - Inicio: index.md
  - Acerca de DeepAgro OWS:
      - Breve Introducción: ows/intro.md
      - Arquitectura: ows/arch.md
  - Acerca de DeepAgro Explorer: explorer.md
  - Servicios:
      - Autorización & autenticación: services/auth.md
      - Configuraciones: services/settings.md
      - Notificaciones: services/notifications.md
      - Datalake: services/datalake.md
      - Anotaciones: services/annotations.md
      - Subida de objetos: services/uploader.md

theme:
  name: material
  logo: img/da-icon-white.png
  favicon: img/favicon.ico

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  analytics:
    provider: google
    property: !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
